-- Monthly P&L snapshot history, generated by the n8n monthly-close workflow.
-- Persists one row per business per closed calendar month so trend/YoY
-- comparisons are possible later without recomputing from raw transactions.
-- Mirrors the bucket structure of profitAndLoss() in src/lib/reports.ts so
-- the automated numbers stay consistent with what the app itself shows.
create table if not exists public.pnl_snapshots (
  id uuid primary key default gen_random_uuid(),
  business_id uuid not null references public.businesses(id) on delete cascade,
  period text not null, -- 'YYYY-MM', the closed month this snapshot covers
  company_type text not null default 'local', -- 'local' | 'international', drives the tax rate
  total_revenue numeric not null default 0,
  total_cogs numeric not null default 0,
  gross_profit numeric not null default 0,
  total_opex numeric not null default 0,
  operating_profit numeric not null default 0,
  total_finance_costs numeric not null default 0,
  profit_before_tax numeric not null default 0,
  tax_expense numeric not null default 0,
  net_profit numeric not null default 0,
  generated_at timestamptz not null default now(),
  unique (business_id, period)
);

alter table public.pnl_snapshots enable row level security;

create policy "Business owns their pnl snapshots"
  on public.pnl_snapshots
  for all
  using (business_id in (select id from public.businesses where owner_id = auth.uid()))
  with check (business_id in (select id from public.businesses where owner_id = auth.uid()));

create policy "service_role_full_pnl_snapshots"
  on public.pnl_snapshots
  for all
  using (auth.role() = 'service_role');
